apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: wibu
spec:
  version: 7.10.0
  nodeSets:
  - name: ganmo
    count: 1
    config:
      node.store.allow_mmap: false
      path.repo: ["/usr/share/elasticsearch/backups"]
